-- Migration: 003_create_conversation_summaries.sql
-- Description: Create table to store conversation summaries
-- Author: System
-- Date: 2025-12-21

CREATE TABLE IF NOT EXISTS conversation_summaries (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  conversation_id UUID NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  text TEXT NOT NULL,
  key_points JSONB DEFAULT '[]'::jsonb,
  technical_details JSONB DEFAULT '{}'::jsonb,
  open_issues JSONB DEFAULT '[]'::jsonb,
  token_count INTEGER NOT NULL DEFAULT 0,
  message_range JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMP DEFAULT NOW(),
  expires_at TIMESTAMP DEFAULT NOW() + INTERVAL '1 hour',
  CONSTRAINT positive_token_count CHECK (token_count >= 0)
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_summaries_conversation_id ON conversation_summaries(conversation_id);
CREATE INDEX IF NOT EXISTS idx_summaries_expires_at ON conversation_summaries(expires_at);
CREATE INDEX IF NOT EXISTS idx_summaries_created_at ON conversation_summaries(created_at DESC);

-- Add comments
COMMENT ON TABLE conversation_summaries IS 'Stores summarized versions of conversations for context window optimization';
COMMENT ON COLUMN conversation_summaries.text IS 'The summary text generated by LLM';
COMMENT ON COLUMN conversation_summaries.key_points IS 'JSON array of key points extracted from summary';
COMMENT ON COLUMN conversation_summaries.technical_details IS 'JSON object containing IPs, hosts, services, errors, etc.';
COMMENT ON COLUMN conversation_summaries.open_issues IS 'JSON array of outstanding questions or problems';
COMMENT ON COLUMN conversation_summaries.message_range IS 'JSON object with start/end/total message counts';
COMMENT ON COLUMN conversation_summaries.expires_at IS 'When this summary should be considered stale (default 1 hour)';

-- Optional: Add a cleanup job to remove expired summaries
-- (This can be done via a cron job or background worker)
-- DELETE FROM conversation_summaries WHERE expires_at < NOW();
